# Generated by Django 4.2.3 on 2023-07-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_conta_icone'),
        ('extrato', '0002_alter_valores_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='perfil.categoria'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='perfil.conta'),
        ),
    ]
