# Generated by Django 4.2.3 on 2023-07-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_conta_icone'),
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapaga',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_paga', to='conta.contapagar'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='perfil.categoria'),
        ),
    ]
