# Generated by Django 4.2.3 on 2023-07-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_banco_nome_alter_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nome',
        ),
    ]
