# Generated by Django 4.2.3 on 2023-07-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planejamento',
            constraint=models.UniqueConstraint(fields=('categoria', 'mes_ano'), name='unique_planejamento'),
        ),
    ]
