# Generated by Django 4.2.3 on 2023-07-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_conta_icone'),
        ('planejamento', '0002_planejamento_unique_planejamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to='perfil.categoria'),
        ),
    ]
